Repository robunye/Projeto-Angular, pull requests merged in 2022-05, with the labels that each got.

#2 Criação da Navbar
  src/app/components/navbar/navbar.component.css
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
Labels: enhancement

#15 Página de Produtos
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/components/produto/produto/produto.component.css
  src/app/components/produto/produto/produto.component.html
  src/app/components/produto/produto/produto.component.spec.ts
  src/app/components/produto/produto/produto.component.ts
  src/app/components/produtos/produtos.component.css
  src/app/components/produtos/produtos.component.html
  src/app/components/produtos/produtos.component.spec.ts
  src/app/components/produtos/produtos.component.ts
  src/app/models/produto.ts
  src/app/shared/services/produtos/produtos.service.spec.ts
  src/app/shared/services/produtos/produtos.service.ts
  src/assets/img/brinco1.jpeg
  src/assets/img/brinco2.jpeg
  src/assets/img/brinco3.jpeg
  src/assets/img/brinco4.jpeg
  src/assets/img/colar1.jpg
  src/assets/img/colar2.jpg
  src/assets/img/colar3.jpg
  src/assets/img/colar4.jpg
  src/assets/img/pulseira1.jpg
  src/assets/img/pulseira2.jpg
  src/assets/img/pulseira3.jpg
  src/assets/img/pulseira4.jpg
  src/assets/img/pulseira5.jpg
  src/assets/img/pulseira6.jpg
  src/assets/img/pulseira7.jpg
  src/assets/img/pulseira8.jpg
  src/assets/img/pulseira9.jpeg
  src/index.html
Labels: enhancement

#16 Página de Erro
  src/app/components/error/error.component.css
  src/app/components/error/error.component.html
  src/app/components/error/error.component.spec.ts
  src/app/components/error/error.component.ts
Labels: enhancement

#17 Adição de Página Novo Produto
  src/app/components/novo-produto/novo-produto.component.css
  src/app/components/novo-produto/novo-produto.component.html
  src/app/components/novo-produto/novo-produto.component.spec.ts
  src/app/components/novo-produto/novo-produto.component.ts
Labels: enhancement

#18 Consumindo API REST Fake
  banco_de_dados.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/cadastro/cadastro.component.css
  src/app/components/cadastro/cadastro.component.html
  src/app/components/cadastro/cadastro.component.spec.ts
  src/app/components/cadastro/cadastro.component.ts
  src/app/components/produto/produto/produto.component.ts
  src/app/components/produtos/produtos.component.ts
  src/app/models/produto.ts
  src/app/shared/services/produtos/produtos.service.ts
  src/app/url_api.ts
Labels: enhancement

#20 Criacao da pagina de cadastro
  banco_de_dados.json
  package-lock.json
  package.json
  src/app/components/cadastro/cadastro.component.css
  src/app/components/cadastro/cadastro.component.html
  src/app/components/cadastro/cadastro.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/components/produtos/produtos.component.css
  src/app/models/usuario-cadastro.ts
  src/app/shared/services/cadastro-service/cadastro.service.ts
  src/app/shared/sweet-alert/sweetalert.ts
  src/index.html
Labels: documentation, enhancement

#21 Criação da página inicial em estilo Landing Page
  banco_de_dados.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/footer/footer.component.css
  src/app/components/footer/footer.component.html
  src/app/components/home/home.component.css
  src/app/components/home/home.component.html
  src/app/components/home/home.component.spec.ts
  src/app/components/home/home.component.ts
  src/app/components/navbar/navbar.component.css
  src/app/components/navbar/navbar.component.html
  src/app/components/produto/produto.component.css
  src/app/components/produto/produto.component.html
  src/app/components/produto/produto.component.spec.ts
  src/app/components/produto/produto.component.ts
  src/assets/img/b1.png
  src/assets/img/b2.png
  src/assets/img/b3.png
  src/assets/img/c1.png
  src/assets/img/c2.png
  src/assets/img/c3.png
  src/assets/img/logoholyjoy.png
Labels: enhancement

#22 Criação da Pagina Login
  banco_de_dados.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/cadastro/cadastro.component.ts
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
  src/app/components/usuario/usuario.component.css
  src/app/components/usuario/usuario.component.html
  src/app/components/usuario/usuario.component.spec.ts
  src/app/components/usuario/usuario.component.ts
  src/app/models/login.ts
  src/app/models/usuario-cadastro.ts
  src/app/shared/services/cadastro-service/cadastro.service.ts
  src/app/shared/sweet-alert/sweetalert.ts
Labels: documentation, enhancement

#23 Pagina de carrinho
  banco_de_dados.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/cadastro/cadastro.component.html
  src/app/components/carrinho/carrinho.component.css
  src/app/components/carrinho/carrinho.component.html
  src/app/components/carrinho/carrinho.component.spec.ts
  src/app/components/carrinho/carrinho.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/login/login.component.html
  src/app/components/navbar/navbar.component.css
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/components/produto/produto.component.html
  src/app/components/produto/produto.component.ts
  src/app/components/produtos/produtos.component.html
  src/app/components/produtos/produtos.component.ts
  src/app/models/dados-cliente.ts
  src/app/models/pedido.ts
  src/app/models/produto.ts
  src/app/shared/carrinho/carrinho.service.ts
  src/app/shared/carrinho/efetivar-compra.service.spec.ts
  src/app/shared/carrinho/efetivar-compra.service.ts
  src/app/shared/services/produtos/produtos.service.ts
Labels: documentation, enhancement

#26 Finalização e Detalhes do Projeto
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/cadastro/cadastro.component.css
  src/app/components/cadastro/cadastro.component.html
  src/app/components/feedback/feedback.component.css
  src/app/components/feedback/feedback.component.html
  src/app/components/footer/footer.component.css
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/usuario/usuario.component.css
  src/app/components/usuario/usuario.component.html
  src/app/components/usuario/usuario.component.spec.ts
  src/app/components/usuario/usuario.component.ts
Labels: documentation

#27 Finalização e Detalhes da página de Carrinho
  src/app/components/carrinho/carrinho.component.html
Labels: documentation
